### ISSUE TITLE
Creating task throws error `type.badge.padEnd is not a function`

### ISSUE THREAD

**Issue by jusopi** [klauscfhq/taskbook#1]
**Describe the bug**
Trying to test out Taskbook, in running the following command `tb -t @work test taskbook` I get the following error:

```
taskbook/node_modules/signale/signale.js:198
      signale.push(chalk[type.color](type.badge.padEnd(type.badge.length + 1)));
                                                ^

TypeError: type.badge.padEnd is not a function
    at Signale._buildSignale (/Users/jusopi/.brews/nvm/versions/node/v6.11.0/lib/node_modules/taskbook/node_modules/signale/signale.js:198:49)
    at Signale._logger (/Users/jusopi/.brews/nvm/versions/node/v6.11.0/lib/node_modules/taskbook/node_modules/signale/signale.js:257:20)
    at Render.successCreate (/Users/jusopi/.brews/nvm/versions/node/v6.11.0/lib/node_modules/taskbook/lib/render.js:248:5)
    at Taskbook.createTask (/Users/jusopi/.brews/nvm/versions/node/v6.11.0/lib/node_modules/taskbook/lib/taskbook.js:325:12)
    at taskbookCLI (/Users/jusopi/.brews/nvm/versions/node/v6.11.0/lib/node_modules/taskbook/index.js:11:21)
    at Object.<anonymous> (/Users/jusopi/.brews/nvm/versions/node/v6.11.0/lib/node_modules/taskbook/cli.js:68:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**To Reproduce**

1. install taskbook via `npm install -g taskbook`
1. create new task `tb -t @work test taskbook`

**Technical Info (please complete the following information)**
 - OS: Mac OS 10.13.6
 - Node.js Version: 
   - node: v6.11.0
   - npm: 3.10.10
 - Taskbook Version: 0.1.1

**Comment by sbacarob** [comment]
@jusopi I got the exact same problem as you. The problem actually comes from Signale, and as pointed out on this [issue](https://github.com/klauscfhq/signale/issues/46), it is a clientside problem which for now can be solved by updating your Nodejs version to the latest.

I updated mine and it did get fixed.

**Comment by jusopi** [comment]
I updated to Node 8.11.3 and it is no longer an issue.  Thank you.

**Comment by Mor-Walkme** [comment]
Works Thanks. i would suggest to add it as a requirement to the readme file.

**Comment by klauscfhq** [comment]
Fixed on https://github.com/klauscfhq/signale/pull/53.
