### ISSUE TITLE
Object function error

### ISSUE THREAD

**Issue by geblix3000** [klauscfhq/taskbook#103]
Hi,

when executing "tb" I get the following error:

```
[user@centos7 ~]$ tb
/usr/lib/node_modules/taskbook/lib/taskbook.js:68
    Object.entries(this._data).forEach(([_, item]) => {
           ^

TypeError: Object.entries is not a function
    at Taskbook._getBoards (/usr/lib/node_modules/taskbook/lib/taskbook.js:68:12)
    at Taskbook._groupByBoard (/usr/lib/node_modules/taskbook/lib/taskbook.js:238:50)
    at Taskbook.displayByBoard (/usr/lib/node_modules/taskbook/lib/taskbook.js:346:32)
    at taskbookCLI (/usr/lib/node_modules/taskbook/index.js:60:12)
    at Object.<anonymous> (/usr/lib/node_modules/taskbook/cli.js:68:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
```

OS: CentOS 7
Installed via npm

**Comment by davialexandre** [comment]
I had the same error. Upgrading node/npm to the latest LTS version fixed the issue

**Comment by geblix3000** [comment]
Hi,

my system (centos7 = EOL 30 Jul 2024) is up to date and running npm version 3.10.10 with node 6.14:

[root@server ~]# npm -v
3.10.10

[root@server ~]# node -v
v6.14.3

To which version you upgraded your npm and node version?

**Comment by davialexandre** [comment]
The latest node and npm LTS version are 8.12.0 and 6.4.10 respectively.

For CentOS, you can get them from the NodeSource repository: https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora
