### ISSUE TITLE
Main program just fails to run

### ISSUE THREAD

**Issue by furqan-shakoor** [klauscfhq/taskbook#20]
Running `tb` throws an exception and quits:

```
/usr/local/lib/node_modules/taskbook/lib/taskbook.js:68
    Object.entries(this._data).forEach(([_, item]) => {
           ^

TypeError: Object.entries is not a function
    at Taskbook._getBoards (/usr/local/lib/node_modules/taskbook/lib/taskbook.js:68:12)
    at Taskbook._groupByBoard (/usr/local/lib/node_modules/taskbook/lib/taskbook.js:238:50)
    at Taskbook.displayByBoard (/usr/local/lib/node_modules/taskbook/lib/taskbook.js:346:32)
    at taskbookCLI (/usr/local/lib/node_modules/taskbook/index.js:60:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/taskbook/cli.js:68:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

**To Reproduce**
1. Install via `npm install --global taskbook`
2. Run `tb`

**Technical Info**
 - OS: MacOS High Sierra
 - Node.js Version: v6.1.0
 - Npm version: 3.8.6
 - Taskbook Version: 0.1.1

**Comment by diegosouza** [comment]
Same here:

- Debian 9.5
- Node v6.2.1
- Npm 3.9.3
- Taskbook 0.1.1

**Comment by astronomersiva** [comment]
You'll have to update node...Object.entries is available from node 7 only(and behind that harmony flag in 6.5).

**Comment by furqan-shakoor** [comment]
Upgraded node and its fixed now

**Comment by diegosouza** [comment]
@furqan-shakoor that's a quick fix to us, but the software keeps broken.
If it requires Node 7, the `package.json` should be updated to `"node": ">=7"` or be fixed to work with Node 6.

**Comment by carywreams** [comment]
If taskbook were also packaged as a snap, would that allow taskbook's "node >= 7" condition to co-exist with those of us who have devops requirements of "node < 7" ?

This is a genuine question. I don't know the answer to the question or even whether node apps can be delivered as snaps. Just hoping earnestly because taskbook is very appealing.

**Comment by omangaresu** [comment]
@carywreams I tried to publish a snap but the name has been reserved maybe by the writer @klauscfhq

**Comment by klauscfhq** [comment]
Fixed on https://github.com/klauscfhq/taskbook/commit/3f818d913a504e389cb3d2d53b7b622c2f1da5cd.
