### ISSUE TITLE
Simple environment error

### ISSUE THREAD

**Issue by williamabrwolf** [klauscfhq/taskbook#28]
**Describe the bug**
I try to run `tb` and I get an error.

**To Reproduce**
Install `npm install --global taskbook` in whatever env I have, and run `tb`/.

**Expected behavior**

Here's the error I get:

```
$ tb

  My Board [0/1]
/Users/myuser/.nvm/versions/node/v7.10.0/lib/node_modules/taskbook/node_modules/signale/signale.js:198
      signale.push(chalk[type.color](type.badge.padEnd(type.badge.length + 1)));
                                                ^

TypeError: type.badge.padEnd is not a function
    at Signale._buildSignale (/Users/myuser/.nvm/versions/node/v7.10.0/lib/node_modules/taskbook/node_modules/signale/signale.js:198:49)
    at Signale._logger (/Users/myuser/.nvm/versions/node/v7.10.0/lib/node_modules/taskbook/node_modules/signale/signale.js:257:20)
    at Render._displayItemByBoard (/Users/myuser/.nvm/versions/node/v7.10.0/lib/node_modules/taskbook/lib/render.js:112:45)
    at items.forEach.item (/Users/myuser/.nvm/versions/node/v7.10.0/lib/node_modules/taskbook/lib/render.js:146:14)
    at Array.forEach (native)
    at Object.entries.forEach (/Users/myuser/.nvm/versions/node/v7.10.0/lib/node_modules/taskbook/lib/render.js:142:13)
    at Array.forEach (native)
    at Render.displayByBoard (/Users/myuser/.nvm/versions/node/v7.10.0/lib/node_modules/taskbook/lib/render.js:137:26)
    at Taskbook.displayByBoard (/Users/myuser/.nvm/versions/node/v7.10.0/lib/node_modules/taskbook/lib/taskbook.js:346:12)
    at taskbookCLI (/Users/myuser/.nvm/versions/node/v7.10.0/lib/node_modules/taskbook/index.js:60:12)
```

**Comment by gotno** [comment]
@williamabrwolf did you find a solution to this? i'm seeing the same thing.

**Comment by klauscfhq** [comment]
Fixed on https://github.com/klauscfhq/signale/pull/53.
