### ISSUE TITLE
Getting error on every execution

### ISSUE THREAD

**Issue by Mor-Walkme** [klauscfhq/taskbook#64]
After installing, i get the following error:
tb --task some task
/usr/lib/node_modules/taskbook/node_modules/signale/signale.js:198
      signale.push(chalk[type.color](type.badge.padEnd(type.badge.length + 1)));
                                                ^

TypeError: type.badge.padEnd is not a function
    at Signale._buildSignale (/usr/lib/node_modules/taskbook/node_modules/signale/signale.js:198:49)
    at Signale._logger (/usr/lib/node_modules/taskbook/node_modules/signale/signale.js:257:20)
    at Render.successCreate (/usr/lib/node_modules/taskbook/lib/render.js:248:5)
    at Taskbook.createTask (/usr/lib/node_modules/taskbook/lib/taskbook.js:325:12)
    at taskbookCLI (/usr/lib/node_modules/taskbook/index.js:11:21)
    at Object.<anonymous> (/usr/lib/node_modules/taskbook/cli.js:68:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)

Some details:
OS: Centos 7
NPM: 3.10.10
Node: v6.14.3

**Comment by rjoydip** [comment]
This is the issue on `Signal` [issue-46](https://github.com/klauscfhq/signale/issues/46). But if you upgrade node version >= 8 then it may resolve. Check this https://github.com/klauscfhq/taskbook/issues/1#issuecomment-409316780

**Comment by klauscfhq** [comment]
Fixed on https://github.com/klauscfhq/signale/pull/53.
