### ISSUE TITLE
TypeError: type.badge.padEnd is not a function

### ISSUE THREAD

**Issue by MrJackJoe** [klauscfhq/taskbook#96]
/usr/local/lib/node_modules/taskbook/node_modules/signale/signale.js:198
      signale.push(chalk[type.color](type.badge.padEnd(type.badge.length + 1)));
                                                ^

TypeError: type.badge.padEnd is not a function
    at Signale._buildSignale (/usr/local/lib/node_modules/taskbook/node_modules/signale/signale.js:198:49)
    at Signale._logger (/usr/local/lib/node_modules/taskbook/node_modules/signale/signale.js:257:20)
    at Render.successCreate (/usr/local/lib/node_modules/taskbook/lib/render.js:248:5)
    at Taskbook.createNote (/usr/local/lib/node_modules/taskbook/lib/taskbook.js:304:12)
    at taskbookCLI (/usr/local/lib/node_modules/taskbook/index.js:19:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/taskbook/cli.js:68:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

This block of text occurs when I run almost all the tb commend. Does anyone know what's happening? Thanks.

**Comment by MrJackJoe** [comment]
find solution at #46
